### ISSUE TITLE
Can't able to install the pointnet2_ops

### ISSUE THREAD

**Issue by vijayraj45** [NVlabs/motion-policy-networks#14]
After cloned the github repo , I try to install it . But it got stuck in the Building wheel for pointnet2-ops command for long time!

[Screenshot_2023-03-28-23-37-06-13](https://user-images.githubusercontent.com/72021479/228329192-8571e425-5037-4598-a4ce-019b6749c636.jpg)

**Comment by fishbotics** [comment]
Building this package can take a very long time. This is because it's set up to build for multiple architectures. If you want to speed up the build process, you could change this line to only build for your architecture: https://github.com/fishbotics/pointnet2_ops/blob/v3.2.0/setup.py#L17

During the build process for the Docker container, I believe the architecture has to be specified (because the build daemon isn't able to access the GPU during build). If you want to automatically detect the architecture on your computer, you could alternatively you could delete that line and remove the package installation from the Dockerfile. This would mean that it's not build as part of the container, but you could then install it inside the docker container after you launch it. When you launch the container, it should have access to the GPU so you'd be able to infer the architecture from there.

**Comment by fishbotics** [comment]
I'm going to close this, but @vijayraj45 feel free to reopen if you're still having issues.
