### ISSUE TITLE
ERROR：import lula

### ISSUE THREAD

**Issue by rangfeng1** [NVlabs/motion-policy-networks#25]
I manage the environment in conda. When I used gen_data, I found that I could not import lula, so I went to download isaac sim. I planned to use the part of downloading isaac sim in your docker, but found that you did not download it in docker ( Maybe it's my lack of knowledge). I use the official download method, it seems very difficult, I would like to ask, how to download isaac sim so that the problem of import lula can be solved.

**Comment by fishbotics** [comment]
I don't use conda and don't know how to make it work within Conda. Isaac Sim is freely available but proprietary, so you won't be able to compile it yourself. The Python version must be 3.7 because that's the version that Lula is compiled for. You may be able to set your PYTHONPATH within the docker to match your conda environment. You may also be able to download Isaac Sim and set your PYTHONPATH on your host machine. These difficulties were a big part of why we released the code with Docker instead of Conda. If you figure it out, please post your setup so that others can learn from you!
