### ISSUE TITLE
Exception has occurred: RuntimeError: Points must be a float tensor

### ISSUE THREAD

**Issue by ThakurSarveshGit** [NVlabs/motion-policy-networks#3]
Hi,

While running the training script with the provided checkpoint and hybrid dataset, I am encountering the following error:

```
Exception has occurred: RuntimeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
points.scalar_type() == at::ScalarType::Float INTERNAL ASSERT FAILED at "PATH/TO/Pointnet2_PyTorch/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/group_points.cpp":15, please report a bug to PyTorch. Points must be a float tensor
```

The fishbotics pointnet_ops package is not installing(getting stuck during installation), hence, tried eric wijman's Pointnet2_PyTorch/pointnet2_ops_lib, which installed fine. There was no issue running/debugging run_inference.py but run_training.py is giving the above error. Problem seems to be with this cpp function call (pointnet2_ops/_ext-src/src/group_points.cpp):
```
        return _ext.group_points(features, idx) # line 214, pointnet2_utils.py
```

features tensor is of type float16 when this error is thrown, when it is float32 there is no error. Why is this happening? Any idea?

NOTE: with features.float() conversion, not getting this error. But not sure why this is happening in the first place.

**Comment by fishbotics** [comment]
The reason why this is happening is that the network is automatically trained with mixed precision (it helps with the scale). The fishbotics version uses templated cuda operations that support multiple tensor types. Erik's only supports float operations (these are specified in the function types in the CUDA code). There are two easy fixes for this:

1. Use the fishbotics version. The build time is long but it should finish. I think mine takes 20 minutes or so. If it doesn't finish, please file an issue on that package and we can discuss it.
2. Turn off mixed precision training by removing this argument: https://github.com/NVlabs/motion-policy-networks/blob/main/mpinets/run_training.py#L112

I would highly recommend option (1) because it will speed up training time, but both should work!
