### ISSUE TITLE
What does the output trajectory numbers represent?

### ISSUE THREAD

**Issue by venishkrishna** [NVlabs/motion-policy-networks#8]
Appreciate your work.what does the output trajectory values represent,joint angles or joint coordinates.

**Comment by fishbotics** [comment]
In short, everything is represented in terms of joint angles, not coordinates. However, it depends on what you mean by output trajectories. 

If you're calling the network using `mdl(xyz, q)`, the input `q` is a set of joint angles that are normalized so that every joint angle is between -1 and 1. Then, the output is actually a displacement `q_delta` that you can add to `q`. At that point, you should clamp the value to be between `-1` and `1` and then unnormalize each joint back into the joint space. You can see an example of this here: https://github.com/NVlabs/motion-policy-networks/blob/main/mpinets/run_inference.py#L172
